import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const Loading = ({ demo }) => {
    return (_jsx("div", { className: "scene-container", "data-testid": "loading-container", style: {
            position: demo ? "relative" : "fixed",
            width: demo ? "500px" : "100%",
            maxHeight: demo ? "500px" : "100%",
        }, children: _jsx("div", { className: "scene", style: {
                position: demo ? "relative" : "fixed",
                width: demo ? "500px" : "",
            }, children: _jsxs("div", { className: "plane", children: [_jsxs("div", { className: "cube cube--0", children: [_jsx("div", { className: "cube__side" }), _jsx("div", { className: "cube__side" }), _jsx("div", { className: "cube__side" }), _jsx("div", { className: "cube__side" }), _jsx("div", { className: "cube__side" }), _jsx("div", { className: "cube__side" })] }), _jsx("div", { className: "shadow shadow--0" }), _jsxs("div", { className: "cube cube--1", children: [_jsx("div", { className: "cube__side" }), _jsx("div", { className: "cube__side" }), _jsx("div", { className: "cube__side" }), _jsx("div", { className: "cube__side" }), _jsx("div", { className: "cube__side" }), _jsx("div", { className: "cube__side" })] }), _jsx("div", { className: "shadow shadow--1" }), _jsxs("div", { className: "cube cube--2", children: [_jsx("div", { className: "cube__side" }), _jsx("div", { className: "cube__side" }), _jsx("div", { className: "cube__side" }), _jsx("div", { className: "cube__side" }), _jsx("div", { className: "cube__side" }), _jsx("div", { className: "cube__side" })] }), _jsx("div", { className: "shadow shadow--2" }), _jsxs("div", { className: "cube cube--3", children: [_jsx("div", { className: "cube__side" }), _jsx("div", { className: "cube__side" }), _jsx("div", { className: "cube__side" }), _jsx("div", { className: "cube__side" }), _jsx("div", { className: "cube__side" }), _jsx("div", { className: "cube__side" })] }), _jsx("div", { className: "shadow shadow--3" }), _jsxs("div", { className: "cube cube--4", children: [_jsx("div", { className: "cube__side" }), _jsx("div", { className: "cube__side" }), _jsx("div", { className: "cube__side" }), _jsx("div", { className: "cube__side" }), _jsx("div", { className: "cube__side" }), _jsx("div", { className: "cube__side" })] }), _jsx("div", { className: "shadow shadow--4" }), _jsxs("div", { className: "cube cube--5", children: [_jsx("div", { className: "cube__side" }), _jsx("div", { className: "cube__side" }), _jsx("div", { className: "cube__side" }), _jsx("div", { className: "cube__side" }), _jsx("div", { className: "cube__side" }), _jsx("div", { className: "cube__side" })] }), _jsx("div", { className: "shadow shadow--5" }), _jsxs("div", { className: "cube cube--6", children: [_jsx("div", { className: "cube__side" }), _jsx("div", { className: "cube__side" }), _jsx("div", { className: "cube__side" }), _jsx("div", { className: "cube__side" }), _jsx("div", { className: "cube__side" }), _jsx("div", { className: "cube__side" })] }), _jsx("div", { className: "shadow shadow--6" }), _jsxs("div", { className: "cube cube--7", children: [_jsx("div", { className: "cube__side" }), _jsx("div", { className: "cube__side" }), _jsx("div", { className: "cube__side" }), _jsx("div", { className: "cube__side" }), _jsx("div", { className: "cube__side" }), _jsx("div", { className: "cube__side" })] }), _jsx("div", { className: "shadow shadow--7" })] }) }) }));
};
export default Loading;
